#!/usr/bin/python

import sys
import IPO
import random

useExact = False

fileName = sys.argv[1]
mils = IPO.MixedIntegerLinearSet(fileName)
if useExact:
  exactOracle = IPO.ExactSCIPOracle(fileName, mils)
  approxOracle = IPO.SCIPOracle(fileName, mils, exactOracle)
else:
  approxOracle = IPO.SCIPOracle(fileName, mils)
submissiveOracle = IPO.SubmissiveOracle('Submissive(' + fileName + ')', approxOracle)
P = IPO.Polyhedron(submissiveOracle)

cons = mils.getConstraints()
lp = IPO.LinearProgram(mils.space)

for i in xrange(10):
  print('Random objective #%d' % (i+1))
  objective = [ (random.random() - 0.5) for i in xrange(lp.numVariables) ]
  lp.changeObjective(objective)

  while True:
    print('Solving LP with %d rows.' % (lp.numRows))
    (status, vector, value) = lp.solve()
    if status == IPO.LinearProgram.OPTIMAL:
      print('LP-optimum: %s' % (vector))
      con = P.separatePoint(vector)
      if con is None:
        break
      print('Separated facet: %s' % (con))
      lp.addConstraint(con)
    elif status == IPO.LinearProgram.UNBOUNDED:
      print('LP-ray: %s' % (vector))
      con = P.separateRay(vector)
      if con is None:
        break
      print('Separated facet: %s' % (con))
      lp.addConstraint(con)
    else:
      assert False
  print
